# Generated by Django 4.2.10 on 2024-02-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=144)),
                ('dirección', models.CharField(max_length=144)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
