# Generated by Django 4.2.10 on 2024-02-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0002_refugio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='refugio_actual',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perros', to='rescate_perros.refugio'),
        ),
    ]
