# Generated by Django 4.2.10 on 2024-02-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0003_perro_refugio_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugio',
            name='dirección',
        ),
        migrations.AddField(
            model_name='refugio',
            name='ciudad',
            field=models.CharField(default='Quito', max_length=144),
        ),
        migrations.AddField(
            model_name='refugio',
            name='direccion',
            field=models.CharField(blank=True, max_length=144),
        ),
    ]
