# Generated by Django 4.2.10 on 2024-02-08 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0004_remove_refugio_dirección_refugio_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('intereses', models.TextField()),
                ('rol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vacunacion', models.DateField()),
                ('vacuna', models.CharField(choices=[('DHPP', 'Distemper, Hepatitis, Parainfluenza and Parvovirus'), ('RABIES', 'Rabies'), ('LEPTO', 'Leptospirosis'), ('BORDETELLA', 'Bordetella Bronchiseptica'), ('LYME', 'Lyme Disease'), ('GIARDIA', 'Giardia'), ('CORONA', 'Coronavirus'), ('HEARTWORM', 'Heartworm Prevention'), ('INFLUENZA', 'Canine Influenza'), ('PARVO', 'Parvovirus'), ('ADENO', 'Adenovirus'), ('DISTEMPER', 'Canine Distemper'), ('HEPATITIS', 'Infectious Canine Hepatitis')], max_length=100)),
                ('certificado', models.CharField(max_length=100)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescate_perros.perro')),
            ],
        ),
        migrations.CreateModel(
            name='InteresadosEnRescatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescate_perros.perro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescate_perros.persona')),
            ],
        ),
        migrations.CreateModel(
            name='AtencionesClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField()),
                ('peso', models.FloatField()),
                ('talla', models.FloatField()),
                ('resumen', models.TextField()),
                ('veterinario', models.CharField(max_length=100)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rescate_perros.perro')),
            ],
        ),
    ]
