# Generated by Django 4.2.10 on 2024-02-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0005_persona_vacuna_interesadosenrescatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], default='male', max_length=6),
            preserve_default=False,
        ),
    ]
