# Generated by Django 4.2.10 on 2024-02-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0006_perro_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='esterilizado',
            field=models.BooleanField(choices=[(True, 'Esterilizado'), (False, 'No Esterilizado')], default=False),
        ),
    ]
