# Generated by Django 4.2.10 on 2024-02-08 23:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0007_perro_esterilizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perro',
            options={'ordering': ['nombre'], 'verbose_name': 'perro', 'verbose_name_plural': 'perros'},
        ),
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del perro.', null=True, upload_to='media/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del perro.', null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='esterilizado',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], default=False, help_text='Indica si el perro está esterilizado.', verbose_name='esterilizado'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de la última actualización del registro.', verbose_name='fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del perro.', null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='ficha_perro',
            field=models.FileField(blank=True, help_text='Ficha médica del perro.', upload_to='uploads/', verbose_name='ficha del perro'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del perro.', max_length=144, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='refugio_actual',
            field=models.ForeignKey(help_text='Refugio en el que se encuentra actualmente el perro.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perros', to='rescate_perros.refugio', verbose_name='refugio actual'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], help_text='Sexo del perro.', max_length=1, verbose_name='sexo'),
        ),
    ]
