# Generated by Django 4.2.10 on 2024-02-15 00:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0008_alter_perro_options_perro_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha de la última actualización del registro.', verbose_name='fecha de actualización'),
        ),
    ]
