# Generated by Django 4.2.10 on 2024-02-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0009_refugio_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='tipo',
            field=models.CharField(blank=True, choices=[('C', 'Campestre'), ('U', 'Urbano')], max_length=5),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='nombre',
            field=models.CharField(help_text='El nombre comercial del refugio o el nombre corto', max_length=144, verbose_name='Nombre del refugio'),
        ),
    ]
