# Generated by Django 4.2.10 on 2024-02-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0010_refugio_tipo_alter_refugio_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='Estado activo de la propiedad'),
        ),
    ]
