# Generated by Django 4.2.10 on 2024-02-15 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0011_refugio_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='documento',
            field=models.FileField(blank=True, help_text='Documento del refugio', upload_to='documentos/', verbose_name='documentos del refugio'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='es_activo',
            field=models.BooleanField(default=True, verbose_name='¿Propiedad activa?'),
        ),
    ]
