# Generated by Django 4.2.10 on 2024-02-16 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0012_refugio_documento_alter_refugio_es_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='ficha_perro',
            field=models.FileField(blank=True, help_text='Ficha médica del perro.', upload_to='media/ficha_perro/', verbose_name='ficha del perro'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del perro.', null=True, upload_to='media/foto_perro/', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='documento',
            field=models.FileField(blank=True, help_text='Documento del refugio', upload_to='media/documentos_refugio/', verbose_name='documentos del refugio'),
        ),
    ]
