# Generated by Django 4.2.10 on 2024-02-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0013_alter_perro_ficha_perro_alter_perro_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refugio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del refugio.', null=True, upload_to='media/foto_refugio/', verbose_name='foto'),
        ),
    ]
