# Generated by Django 4.2.10 on 2024-02-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0014_refugio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refugio',
            name='documento',
            field=models.FileField(blank=True, help_text='Documento del refugio', upload_to='documentos_refugio/', verbose_name='documentos del refugio'),
        ),
        migrations.AlterField(
            model_name='refugio',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto del refugio.', null=True, upload_to='foto_refugio/', verbose_name='foto'),
        ),
    ]
