# Generated by Django 4.2.10 on 2024-02-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescate_perros', '0015_alter_refugio_documento_alter_refugio_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=255, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_usuario', models.FileField(blank=True, upload_to='foto_usuario/')),
            ],
        ),
    ]
